GENERAL:
  name: apple2orange
  rgb: False
  batch_size: 32
  resolution: &resolution [ 256, 256 ]
  max_epochs: 1000
  num_workers: 8
  data:
    train:
      default:
        - ./datasets/apple2orange/train
    test:
      default:
        - ./datasets/apple2orange/test
  net_init:
    init_type: normal
    init_gain: 0.02

CLASSIFIER:
  model:
    type: torchvision.models.efficientnet_b0
    params:
      num_classes: 2
      weights: DEFAULT
  optimizer:
    type: monai.optimizers.Novograd
    params:
      amsgrad: True
      lr: 5.0e-4
      weight_decay: 0.001
  scheduler:
    type: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
      T_0: 200
      T_mult: 2
      eta_min: 1.0e-6

CUT:
  flip_equivariance: False
  lambda_GAN: 1.0
  lambda_NCE: 1.0
  nce_layers: [ 0,4,8,12,16 ]
  nce_T: 0.07
  nce_idt: True
  mode: lsgan
  netG:
    params:
      ngf: 64
      norm: batch
      use_dropout: False
      n_blocks: 9
      padding_type: reflect
      no_antialias: False
      no_antialias_up: False
    optimizer:
      type: torch.optim.AdamW
      params:
        lr: 5.0e-4
        betas: [ 0.75, 0.999 ]
        weight_decay: 1.0e-3
    scheduler:
      type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
      params:
        T_0: 2500
        T_mult: 2
        eta_min: 0.00005
  netD:
    params:
      ndf: 64
      n_layers: 3
      no_antialias: False
      norm: batch
    optimizer:
      type: torch.optim.AdamW
      params:
        lr: 5.0e-4
        betas: [ 0.75, 0.999 ]
        weight_decay: 1.0e-3
    scheduler:
      type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
      params:
        T_0: 2500
        T_mult: 2
        eta_min: 0.00005
  netF:
    params:
      use_mlp: True
      nc: 256
      num_patches: 64
    optimizer:
      type: torch.optim.AdamW
      params:
        lr: 2.0e-4
        betas: [ 0.75, 0.999 ]
        weight_decay: 1.0e-3
    scheduler:
      type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
      params:
        T_0: 2500
        T_mult: 2
        eta_min: 0.00002

AUGMENTATION:
  RandomHorizontalFlip:
    origin: torchvision.transforms
    params:
      p: 0.5
  RandomVerticalFlip:
    origin: torchvision.transforms
    params:
      p: 0.5
  RandomResizedCrop:
    origin: torchvision.transforms
    params:
      size: *resolution
      scale: !!python/tuple [ 0.6, 0.95 ]



