GENERAL:
  name: IPAD
  seed: 47
  rgb: False
  resolution: &resolution [ 128, 128 ]
  max_epochs: 1000
  pad_token_id: -1
  data:
    train:
#      IrisCSD:
#        config:
#          skip: True
#        paths:
#          - /data/dataset/IrisCSD
      IIIT_WVU:
        config:
          skip: False
        paths:
          - /data/dataset/LivDet2017/IIIT_WVU/train
#      Clarkson:
#        config:
#          skip: True
#        paths:
#          - /data/dataset/LivDet2017/Clarkson/train
#      NotreDame:
#        config:
#          skip: True
#        paths:
#          - /data/dataset/LivDet2017/NotreDame/train
    test:
#      Clarkson:
#        config:
#          gan: True
#        paths:
#          - /data/dataset/LivDet2017/Clarkson/test
      IIIT_WVU:
        config:
          gan: True
        paths:
          - /data/dataset/LivDet2017/IIIT_WVU/test
#      NotreDame:
#        config:
#          gan: True
#        paths:
#          - /data/dataset/LivDet2017/NotreDame/test
  net_init:
    init_type: normal
    init_gain: 0.02

CLASSIFIER:
  batch_size: 64
  warmup: 40
  model:
    type: torchvision.models.efficientnet_b0
    params:
      weights: DEFAULT
    replacements:
      - name: "features.0.0"
        type: torch.nn.Conv2d
        params:
          in_channels: 1
          out_channels: 32
          kernel_size: 3
          stride: 2
          padding: 1
          bias: False
      - name: "classifier.1"
        type: torch.nn.Linear
        params:
          in_features: 1280
          out_features: 2
          bias: True
  optimizer:
    type: monai.optimizers.Novograd
    params:
      amsgrad: False
      lr: 3.0e-3
      weight_decay: 1.0e-3
  scheduler:
    type: transformers.get_cosine_with_hard_restarts_schedule_with_warmup
    params:
      num_cycles: 5
      num_warmup_steps: 1000
      num_training_steps: -1

CUT:
  flip_prob: 0.2
  batch_size: 32
  apply: True
  iterative: True
  update_freq: 5
  warmup: 20
  flip_equivariance: False
  lambda_GAN: 1.0
  lambda_NCE: 10.0
  nce_layers: [ 0,4,8,12,16,20 ]
  nce_T: 0.07
  nce_idt: True
  mode: lsgan
  netG:
    params:
      ngf: 128
      norm: batch
      use_dropout: False
      n_blocks: 6
      padding_type: reflect
      no_antialias: False
      no_antialias_up: False
    optimizer:
      type: monai.optimizers.Novograd
      params:
        lr: 5.0e-4
        betas: [ 0.75, 0.999 ]
        weight_decay: 1.0e-3
    scheduler:
      type: transformers.get_cosine_schedule_with_warmup
      params:
        num_warmup_steps: 1000
        num_training_steps: -1
  netD:
    params:
      ndf: 128
      n_layers: 3
      no_antialias: False
      norm: batch
    optimizer:
      type: monai.optimizers.Novograd
      params:
        lr: 5.0e-4
        betas: [ 0.75, 0.999 ]
        weight_decay: 1.0e-3
    scheduler:
      type: transformers.get_cosine_schedule_with_warmup
      params:
        num_warmup_steps: 1000
        num_training_steps: -1
  netF:
    params:
      use_mlp: True
      nc: 256
      num_patches: 128
    optimizer:
      type: monai.optimizers.Novograd
      params:
        lr: 1.0e-3
        betas: [ 0.75, 0.999 ]
        weight_decay: 1.0e-3
    scheduler:
      type: transformers.get_cosine_schedule_with_warmup
      params:
        num_warmup_steps: 1000
        num_training_steps: -1

AUGMENTATION:
  RandomHorizontalFlip:
    origin: torchvision.transforms
    params:
      p: 0.5
  RandomVerticalFlip:
    origin: torchvision.transforms
    params:
      p: 0.5
  RandomResizedCrop:
    origin: torchvision.transforms
    params:
      size: *resolution
      scale: !!python/tuple [ 0.6, 0.95 ]



